change release.yml to extract version from pom.xml file

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -13,6 +13,12 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Set up JDK (for Maven) for pom.xml file read
+        uses: actions/setup-java@v4
+        with:
+            distribution: 'temurin'
+            java-version: '17'
+
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v3
         with:
@@ -20,22 +26,35 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GH_TOKEN }}
 
-      - name: Parse the version from version tag
+      - name: Parse the version from pom.xml file and validate it
         run: |
-          VERSION=${GITHUB_REF:11}
-          MAJOR=$(echo "$VERSION" | cut -d . -f 1)
-          MINOR=$(echo "$VERSION" | cut -d . -f 2)
-          PATCH=$(echo "$VERSION" | cut -d . -f 3)
-          echo "version=$VERSION" >> $GITHUB_ENV
+          #1. Read version pom.xml using MVN
+          
+          IMG_POM_VERSION=$(mvn -q -Dexec.cleanupDaemonThreads=false help:evaluate -D expression=project.version -D forceStdout)
+          echo "Version found in pom.xml: $IMG_POM_VERSION"
+
+          #2. Extract information from tag by stripping first 11 chars
+          
+          TAG_VERSION=${GITHUB_REF:11}
+          echo "Version from tag: $TAG_VERSION"
+
+          #3. Validate the similarity btw tag version from pom.xml and github
+          
+          if [ "$IMG_POM_VERSION" != "$TAG_VERSION" ]; then
+            echo "ERROR: pom.xml version ($IMG_POM_VERSION) does not match tag version ($TAG_VERSION)"
+            exit 1
+          fi
+          
+          NEW_VERSION="$IMG_POM_VERSION"
+          
+          MAJOR=$(echo "$NEW_VERSION" | cut -d . -f 1)
+          MINOR=$(echo "$NEW_VERSION" | cut -d . -f 2)
+          PATCH=$(echo "$NEW_VERSION" | cut -d . -f 3)
+          
+          echo "version=$NEW_VERSION" >> $GITHUB_ENV
           echo "version_major=$MAJOR" >> $GITHUB_ENV
           echo "version_minor=$MINOR" >> $GITHUB_ENV
           echo "version_patch=$PATCH" >> $GITHUB_ENV
-
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
 
       - name: Build and push to registry
         run: |
